"""Stable public types for embedding Windcode."""

from windcode.domain.events import (
    AgentEventType,
    ApprovalRequested,
    ApprovalResponse,
    RunRequest,
    RunResponse,
    RunResult,
    SubagentBlocked,
    SubagentCancelled,
    SubagentCleanup,
    SubagentCompleted,
    SubagentConflict,
    SubagentFailed,
    SubagentIntegrated,
    SubagentProgress,
    SubagentQueued,
    SubagentStarted,
    UserInputRequested,
    UserResponse,
)
from windcode.domain.subagents import (
    SubagentRecord,
    SubagentResult,
    SubagentRole,
    SubagentStatus,
    SubagentTaskKind,
    SubagentTaskSpec,
    VerificationResult,
)
from windcode.domain.tools import Tool, ToolContext, ToolEffect, ToolResult

AgentEvent = AgentEventType

__all__ = [
    "AgentEvent",
    "ApprovalRequested",
    "ApprovalResponse",
    "RunRequest",
    "RunResponse",
    "RunResult",
    "SubagentBlocked",
    "SubagentCancelled",
    "SubagentCleanup",
    "SubagentCompleted",
    "SubagentConflict",
    "SubagentFailed",
    "SubagentIntegrated",
    "SubagentProgress",
    "SubagentQueued",
    "SubagentRecord",
    "SubagentResult",
    "SubagentRole",
    "SubagentStarted",
    "SubagentStatus",
    "SubagentTaskKind",
    "SubagentTaskSpec",
    "Tool",
    "ToolContext",
    "ToolEffect",
    "ToolResult",
    "UserInputRequested",
    "UserResponse",
    "VerificationResult",
]
